# permissions for end users to view ipsecconns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipsecconn-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-combo
    app.kubernetes.io/part-of: kube-combo
    app.kubernetes.io/managed-by: kustomize
  name: ipsecconn-viewer-role
rules:
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - ipsecconns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpn-gw.kubecombo.com
  resources:
  - ipsecconns/status
  verbs:
  - get
